/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

import org.gradle.external.javadoc.StandardJavadocDocletOptions

version = "0.1"

plugins {
    java

    id("org.openjfx.javafxplugin") version "0.0.14"
    id("com.gradleup.shadow") version "8.3.0"
    // Apply CheckStyle plugin
    checkstyle
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)

    val javaFxVersion = "17.0.9"
    implementation(group = "org.openjfx", name = "javafx-base", version = javaFxVersion, classifier = "win")
    implementation(group = "org.openjfx", name = "javafx-base", version = javaFxVersion, classifier = "mac-aarch64")
    implementation(group = "org.openjfx", name = "javafx-base", version = javaFxVersion, classifier = "linux")
    implementation(group = "org.openjfx", name = "javafx-controls", version = javaFxVersion, classifier = "win")
    implementation(group = "org.openjfx", name = "javafx-controls", version = javaFxVersion, classifier = "mac-aarch64")
    implementation(group = "org.openjfx", name = "javafx-controls", version = javaFxVersion, classifier = "linux")
    implementation(group = "org.openjfx", name = "javafx-fxml", version = javaFxVersion, classifier = "win")
    implementation(group = "org.openjfx", name = "javafx-fxml", version = javaFxVersion, classifier = "mac-aarch64")
    implementation(group = "org.openjfx", name = "javafx-fxml", version = javaFxVersion, classifier = "linux")
    implementation(group = "org.openjfx", name = "javafx-graphics", version = javaFxVersion, classifier = "win")
    implementation(group = "org.openjfx", name = "javafx-graphics", version = javaFxVersion, classifier = "mac-aarch64")
    implementation(group = "org.openjfx", name = "javafx-graphics", version = javaFxVersion, classifier = "linux")
}


testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnit("4.13.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.register<JavaExec>("run") {
    mainClass.set("jack.Launcher")
    classpath = sourceSets.main.get().runtimeClasspath
    standardInput = System.`in`
    workingDir = project.rootDir
}

// Configure Javadoc task to generate documentation in root ./doc directory
tasks.javadoc {
    destinationDir = file("${project.rootDir}/doc")
    options.encoding = "UTF-8"
    options.overview = null
    options.locale = "en_US"

    // Include all Java files in the jack package
    source = sourceSets["main"].allJava
}

tasks.jar {
    archiveFileName.set("Jack-v"+version+".jar")
    manifest {
        attributes["Main-Class"] = "jack.Launcher"
    }
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
    }) {
        exclude("META-INF/*.SF")
        exclude("META-INF/*.DSA")
        exclude("META-INF/*.RSA")
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.shadowJar {
    archiveFileName.set("Jack-v"+version+".jar")
    manifest {
        attributes["Main-Class"] = "jack.Launcher"
    }
}

// Configure CheckStyle
checkstyle {
    toolVersion = "11.0.0"
    configFile = file("${project.rootDir}/config/checkstyle/checkstyle.xml")
}

// Add CheckStyle task to build lifecycle
tasks.build {
    dependsOn(tasks.checkstyleMain)
    dependsOn(tasks.checkstyleTest)
}
